### ISSUE TITLE
"SauceConnect" error appears regardless of root cause

### ISSUE THREAD

**Issue by mmerrell** [kgress/scaffold#21]
# Bug
Whenever you run into a config issue with Sauce tests, the following error appears:
java.lang.RuntimeException: io.github.kgress.scaffold.exception.WebDriverContextException: Error initializing remote session against SAUCE. Check to ensure your Sauce TunnelIdentifier has been initialized prior to running your tests.

# Expected
This error message appears when the username/access key is wrong, not just when the tunnel is down.

# Repro
Add steps to reproduce the behavior. E.G:
1. Change your 'desired-capabilities.sauce.access-key' property to be something invalid
2. Run a test
3. You will see the error message about the SauceConnect tunnel

**Comment by kgress** [comment]
This is being fixed in issue #20
