### ISSUE TITLE
Deployment failure on npm version with travis

### ISSUE THREAD

**Issue by kgress** [kgress/scaffold#78]
# Bug
During deployment for 2.9.0, an unexpected error occurred when finding the previous version

```
npx: installed 68 in 5.34s
yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
```

It's possible the VM for the deployment gave us a node version below 10. 

# Expected
We should find a way to specify the node version to get around this issue

**Comment by tkoop** [comment]
I just found this page because I Googled "yargs parser supports a minimum Node.js version of ".  Maybe someone could post an answer here to what we are supposed to do when we find this error.

**Comment by tkoop** [comment]
> I just found this page because I Googled "yargs parser supports a minimum Node.js version of ". Maybe someone could post an answer here to what we are supposed to do when we find this error.

If someone else finds this page, this is how I fixed this issue:
```
npm uninstall yargs
npm install minimist
```

**Comment by kgress** [comment]
> > I just found this page because I Googled "yargs parser supports a minimum Node.js version of ". Maybe someone could post an answer here to what we are supposed to do when we find this error.
> 
> If someone else finds this page, this is how I fixed this issue:
> 
> ```
> npm uninstall yargs
> npm install minimist
> ```

Hi there tkoop,

This ticket was filed due to Travis CI choosing a VM using a version of Node < 10.x. Since Scaffold uses semver, we had to update the deploy in Travis to always use at least version 10.

**Comment by joargp** [comment]
@kgress would you mind sharing how you did that? We have the same issue
