### ISSUE TITLE
Add a desired capability for explicit wait length

### ISSUE THREAD

**Issue by kgress-heb** [kgress/scaffold#92]
# Summary
Currently, Scaffold does not allow the user to easily set a desired explicit wait length through the spring profile, or desired capabilities. Furthermore, there are different wait times between `WebDriverManager` and `AutomationWait`. The current work around for setting a desired time is programmatically through code - e.g., ```getWebDriverWrapper().getAutomationWait().setCustomTimeout(DESIRED_WAIT_PERIOD)```. I believe this to be counter intuitive. We should address this issue by adding in a new desired capability for wait time and use this wait length for both files. 

# A/C
* Scaffold should allow the user to set their desired wait time through desired capabilities

**Comment by kgress** [comment]
included in #95
